import type { IngredientCategory } from "../../types/recipe";
import type { ShoppingItem, ShoppingList } from "../../types/shoppingList";

/**
 * This function calculates the total cost of the shopping list based on the category
 * This code was generated by IA
 * @param {any} items:Map<IngredientCategory
 * @param {any} ShoppingItem[]>
 * @returns {any}
 */
function calculateTotalCost(
  items: Map<IngredientCategory, ShoppingItem[]>
): number {
  let total = 0;
  items.forEach((list) => {
    list.forEach((item) => {
      if (!item.haveAlready && item.price) {
        total += item.price;
      }
    });
  });
  return parseFloat(total.toFixed(2));
}

/**
 * This function add or merge the ingredient in the list
 * Add a new ingredient but if there is already an ingredient by id or name
 * It merges the quantity only
 * It was also created by IA
 * @param {any} list:Map<IngredientCategory
 * @param {any} ShoppingItem[]>
 * @param {any} item:ShoppingItem
 * @returns {any}
 */
function addOrMergeItem(
  list: Map<IngredientCategory, ShoppingItem[]>,
  item: ShoppingItem
): Map<IngredientCategory, ShoppingItem[]> {
  const categoryItems = list.get(item.category) || [];

  const existing = categoryItems.find(
    (i) => i.id === item.id || i.name.toLowerCase() === item.name.toLowerCase()
  );

  if (existing) {
    existing.quantity += item.quantity;
  } else {
    categoryItems.push(item);
  }

  list.set(item.category, categoryItems);
  return list;
}

/**
 * After doing some tests it was realized that Map cannot be serialized
 * So not to create all the code again this function was created to convert map into simple object
 * @param {any} map:Map<IngredientCategory
 * @param {any} ShoppingItem[]>
 * @returns {any}
 */
function mapToShoppingList(
  map: Map<IngredientCategory, ShoppingItem[]>
): ShoppingList {
  const obj: ShoppingList = {} as ShoppingList;

  map.forEach((items, category) => {
    obj[category] = items;
  });

  return obj;
}

/**
 * This function convert the opposite of the above
 * It converts the simple object into Map
 * @param {any} list:ShoppingList
 * @returns {any}
 */
function shoppingListToMap(
  list: ShoppingList
): Map<IngredientCategory, ShoppingItem[]> {
  const map = new Map<IngredientCategory, ShoppingItem[]>();

  (Object.keys(list) as IngredientCategory[]).forEach((category) => {
    map.set(category, list[category] ?? []);
  });

  return map;
}

export default {
  calculateTotalCost,
  addOrMergeItem,
  mapToShoppingList,
  shoppingListToMap,
};
